branch-defaults:
  default:
    environment: django-env-v5
    group_suffix: null
global:
  application_name: django-tutorial-v5
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
